/**
 * PIANOSENSE - External Data Synchronization Engine
 * Injects local Python OMR note streams into the interactive visual highway loop.
 */

async function syncPythonDecoderData() {
    const titleElement = document.getElementById('currentSongTitle');
    const tempoElement = document.getElementById('currentSongTempo');
    const terminalConsole = document.getElementById('omrTerminal');

    console.log("Attempting to load decoded song metrics from song_data.json...");
    
    try {
        // Fetch the file generated by your local Python pixel scan execution
        const response = await fetch('song_data.json');
        if (!response.ok) {
            throw new Error("song_data.json file not found on local root directory.");
        }
        
        const decodedSong = await response.json();
        
        if (!decodedSong.notes || decodedSong.notes.length === 0) {
            throw new Error("Target file contains empty note arrays.");
        }

        // Assign unique structural ID parameters to prevent caching errors
        decodedSong.id = "decoded-run-" + Date.now();

        // Push into the main client framework song array list
        if (typeof SONG_LIBRARY !== 'undefined') {
            // Remove previous scanned versions if they exist to keep memory fresh
            const existingIdx = SONG_LIBRARY.findIndex(s => s.composer === "Yousician Visual Engine");
            if (existingIdx !== -1) {
                SONG_LIBRARY.splice(existingIdx, 1);
            }
            
            SONG_LIBRARY.unshift(decodedSong);
        }

        // Call the app's internal loader sequence to switch viewports over to the new song
        if (typeof selectSong === 'function') {
            selectSong(decodedSong);
        } else {
            // Fallback text rendering adjustments if layout UI isn't fully drawn yet
            if (titleElement) titleElement.innerText = decodedSong.title;
            if (tempoElement) tempoElement.innerText = `${decodedSong.tempo} BPM`;
        }

        // Print success log entry directly into the dark console module UI element
        if (terminalConsole) {
            const successDiv = document.createElement('div');
            successDiv.className = "text-emerald-400 font-bold";
            successDiv.innerText = `[${new Date().toLocaleTimeString()}] Custom OMR Sync: Loaded ${decodedSong.notes.length} highway note blocks cleanly!`;
            terminalConsole.appendChild(successDiv);
            terminalConsole.scrollTop = terminalConsole.scrollHeight;
        }

    } catch (error) {
        console.error("Sync interface error state:", error.message);
        if (terminalConsole) {
            const errorDiv = document.createElement('div');
            errorDiv.className = "text-red-400";
            errorDiv.innerText = `[${new Date().toLocaleTimeString()}] Local Sync Failed: ${error.message}`;
            terminalConsole.appendChild(errorDiv);
        }
    }
}

// Add event listener bindings to the UI buttons when the window mounts completely
document.addEventListener('DOMContentLoaded', () => {
    // Intercept the "Offline Scan" button to serve as the local Python pipeline syncer
    const syncButton = document.getElementById('engineLocalBtn');
    if (syncButton) {
        syncButton.innerText = "Sync Python File";
        syncButton.addEventListener('click', (e) => {
            e.preventDefault();
            syncPythonDecoderData();
        });
    }
});
